### ISSUE TITLE
`ScatterLinear` error

### ISSUE THREAD

**Issue by mitkotak** [mitkotak/export_debug#1]
- Linear + Scatter fails
```
./build/inference /home/mkotak/atomic_architects/projects/export_debug/export/scatter_linear_error/model.so
scatter successfull
unknown:0: unknown: block: [0,0,0], thread: [1,0,0] Assertion `index out of bounds: 0 <= tmp4 < 32` failed.
unknown:0: unknown: block: [0,0,0], thread: [3,0,0] Assertion `index out of bounds: 0 <= tmp4 < 32` failed.
unknown:0: unknown: block: [0,0,0], thread: [5,0,0] Assertion `index out of bounds: 0 <= tmp4 < 32` failed.
unknown:0: unknown: block: [0,0,0], thread: [7,0,0] Assertion `index out of bounds: 0 <= tmp4 < 32` failed.
unknown:0: unknown: block: [0,0,0], thread: [8,0,0] Assertion `index out of bounds: 0 <= tmp4 < 32` failed.
unknown:0: unknown: block: [0,0,0], thread: [10,0,0] Assertion `index out of bounds: 0 <= tmp4 < 32` failed.
unknown:0: unknown: block: [0,0,0], thread: [14,0,0] Assertion `index out of bounds: 0 <= tmp4 < 32` failed.
unknown:0: unknown: block: [0,0,0], thread: [15,0,0] Assertion `index out of bounds: 0 <= tmp4 < 32` failed.
unknown:0: unknown: block: [0,0,0], thread: [16,0,0] Assertion `index out of bounds: 0 <= tmp4 < 32` failed.
unknown:0: unknown: block: [0,0,0], thread: [19,0,0] Assertion `index out of bounds: 0 <= tmp4 < 32` failed.
unknown:0: unknown: block: [0,0,0], thread: [21,0,0] Assertion `index out of bounds: 0 <= tmp4 < 32` failed.
unknown:0: unknown: block: [0,0,0], thread: [22,0,0] Assertion `index out of bounds: 0 <= tmp4 < 32` failed.
unknown:0: unknown: block: [0,0,0], thread: [23,0,0] Assertion `index out of bounds: 0 <= tmp4 < 32` failed.
unknown:0: unknown: block: [0,0,0], thread: [24,0,0] Assertion `index out of bounds: 0 <= tmp4 < 32` failed.
Error: CUDA driver error: device-side assert triggered
terminate called after throwing an instance of 'std::runtime_error'
  what():  run_func_( container_handle_, input_handles.data(), input_handles.size(), output_handles.data(), output_handles.size(), cuda_stream_handle, proxy_executor_handle_) API call failed at ../torch/csrc/inductor/aoti_runner/model_container_runner.cpp, line 75
make: *** [Makefile:18: error] Aborted (core dumped)
```

- Scatter only works
```
(.venv) mkotak@radish:~/atomic_architects/projects/export_debug$ make works 
./build/inference /home/mkotak/atomic_architects/projects/export_debug/export/scatter_works/model.so
call successfull
```

**Comment by mitkotak** [comment]
Let's do a one to one matching between the python code and the underlying C++ code. With some good old printing was able to narrow it down to [one of the](https://github.com/mitkotak/export_debug/blob/93f7257d3aea6c58da79e08641fe1d41de913e8c/export/scatter_linear_error/cwkmv6226wf624rhqclwkglrwlhomjeibtwutrg32fslyqcu2jda.cpp#L632-L641) linear kernels that is launched right after the scatter.

**Comment by mitkotak** [comment]
What is that kernel actually doing ? It seems to be doing a [simple memory copy ](https://github.com/mitkotak/export_debug/blob/93f7257d3aea6c58da79e08641fe1d41de913e8c/torch_compile_debug/scatter_linear_error/torchinductor/model___0.0/output_code.py#L105-L133) probably to prep things for the aten.mm call which [applies the weight ](https://github.com/mitkotak/export_debug/blob/93f7257d3aea6c58da79e08641fe1d41de913e8c/torch_compile_debug/scatter_linear_error/torchinductor/model___0.0/output_code.py#L216-L218)(only one in this case).

**Comment by mitkotak** [comment]
I think the issue is definitely in the scatter kernel somewhere since [this ](https://github.com/mitkotak/export_debug/blob/93f7257d3aea6c58da79e08641fe1d41de913e8c/torch_compile_debug/scatter_linear_error/torchinductor/model___0.0/output_code.py#L100) particular assert seems to be getting triggered (There are only 2 places where tmp4 is used and the other one is the last kernel which we never reach)

**Comment by TaufeqRazakh** [comment]
@mitkotak I haven't tested this yet, but I see there is an O3.Linear module used. This module has graph breaks when I tested this independently. Could this be a reason ?

**Comment by mitkotak** [comment]
I think turning off jit solves that issue. Also export would scream and won't create the kernels at all. The thing that's weird is that this works when you load up the binary in python

**Comment by TaufeqRazakh** [comment]
> I think turning off jit solves that issue. Also export would scream and won't create the kernels at all. The thing that's weird is that this works when you load up the binary in python

Yep, turning off jit solves that issue. Currently looking into the import issue

**Comment by mitkotak** [comment]
If you are looking for a cleaner way of doing things `prepare` function [here](https://github.com/e3nn/e3nn/pull/455)

**Comment by TaufeqRazakh** [comment]
Just to recap, inference in cpp works on this repo but not `e3nn_tetris` ? 

Also wanted to ask which one was tested for inference in Python? 
> The thing that's weird is that this works when you load up the binary in Python

**Comment by mitkotak** [comment]
> Just to recap, inference in cpp works on this repo but not on `e3nn_tetris` ?

Both `Scatter` and `ScatterLinear` are subsets are of `e3nn_tetris`. Inference is not working anywhere currently. Only in the just `Scatter` subset.

> Also wanted to ask which one was tested for inference in Python?

All of them. `torch._export.aot_load` should work on everything.

**Comment by TaufeqRazakh** [comment]
I believe `run.py` only produces `Scatter` only subset ?https://github.com/mitkotak/export_debug/blob/93f7257d3aea6c58da79e08641fe1d41de913e8c/run.py#L73

How to get the `ScatterLinear` subset .so

**Comment by mitkotak** [comment]
[this](https://github.com/mitkotak/export_debug/blob/93cd25b14d2733b519d60164fa20e964bf5609bf/run.py#L65) should do it. Sorry for the sloppiness in the modularity

**Comment by mitkotak** [comment]
Hard coding the values made it work !
